server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/trackpoint
  mail:
    host: smtp.163.com
    username: greatqiaoyi@163.com
    password: FGp43p4Pe2muYKw6
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  websocket:
    enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
